### ISSUE TITLE
GraphiQL JsonMappingException

### ISSUE THREAD

**Issue by heruan** [graphql-java/graphql-java-servlet#33]
Querying with GraphiQL I get this exception:
```
Error executing GraphQL request!: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.util.LinkedHashMap: no String-argument constructor/factory method to deserialize from String value ('{}')
 at [Source: "{}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:315)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2861)
	at graphql.servlet.GraphQLServlet.lambda$new$0(GraphQLServlet.java:108)
	at graphql.servlet.GraphQLServlet.doRequest(GraphQLServlet.java:224)
	at graphql.servlet.GraphQLServlet.doGet(GraphQLServlet.java:237)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        ...
```

It seems like `variables` are an empty JSON object `{}` and it fails parsing, isn't it?

**Comment by apottere** [comment]
What version of GraphiQL are you using?  I'll take a look.

**Comment by heruan** [comment]
Thank you! I'm using https://github.com/skevy/graphiql-app which depends on GraphiQL 0.10.2.
